### ISSUE TITLE
JS and TS files are duplicates

### ISSUE THREAD

**Issue by Rudxain** [Benricheson101/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#135]
I know Typescript is a superset of Javascript, but we can add subtle differences that are typical of both langs. The JS file could use `while (1)` or `while (Infinity)` loops. The Typescript file could use a statically-typed bool variable set to `true`, and a string var with the value 'a'. This would add "personality" and uniqueness to both files

**Comment by Benricheson101** [comment]
I don't see why that's needed? It's just coincidental that they're the same. Going out of the way to use intentionally bad practices (`while (1)`, `while (Infinity)`, typed bool variable) isn't something I see any point to.

**Comment by Rudxain** [comment]
`while (1)` isn't that bad, but I understand it may not be a good idea. The main purpose of my suggestion is that they should be *at least* slightly different (in any way). It doesn't need to be exactly what I said about loops
