### ISSUE TITLE
Thanks to this repo I found a GH bug

### ISSUE THREAD

**Issue by Rudxain** [Benricheson101/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#140]
![](https://i.imgur.com/Ij1r05T.jpeg)

Yep, that's a text overflow that only happens in the mobile layout of the website (not the app)

I love this repo lol

**Comment by thenithinbalaji** [comment]
one of the reasons why i want my PR to be merged or closed 😭
